### Get all available appointments
GET {{url}}/api/appointments
Authorization: Basic student1 password

### Take appointment
POST {{url}}/api/appointments/reserve/135
Authorization: Basic student1 password

### Get all reserved appointments
GET {{url}}/api/appointments/reserved
Authorization: Basic student1 password

### Free appointment
POST {{url}}/api/appointments/free/139
Authorization: Basic student1 password

### Trigger appointment creation task
POST {{url}}/api/admin/appointments
Authorization: Basic admin1 admin
