### Get all available appointments
GET localhost:8080/api/appointments
Authorization: Basic student1 password

### Take appointment
POST localhost:8080/api/appointments/reserve/135
Authorization: Basic student1 password

### Get all reserved appointments
GET localhost:8080/api/appointments/reserved
Authorization: Basic student1 password

### Free appointment
POST localhost:8080/api/appointments/free/139
Authorization: Basic student1 password
