### Get all Students
GET {{url}}/api/users/students
Authorization: Basic admin1 admin

### Get all Users
GET {{url}}/api/users
Authorization: Basic admin1 admin

### Get all Students as a Student
GET {{url}}/api/users/students
Authorization: Basic student1 password


