### Get all Students
GET localhost:8080/api/users/students
Authorization: Basic admin1 admin

### Get all Users
GET localhost:8080/api/users
Authorization: Basic admin1 admin

### Get all Students as a Student
GET localhost:8080/api/users/students
Authorization: Basic student1 password


