### View all free and future appointments
GET localhost:8080/api/appointments
Authorization: Basic student1 password

### Reserve Appointment
POST localhost:8080/api/appointments/reserve/29
Authorization: Basic student1 password

### View my reservations
GET localhost:8080/api/appointments/reserved
Authorization: Basic student1 password

### Start exam
GET localhost:8080/exams/start?key=393fb5c5-a7ed-477b-a95c-cd337af89ae9
Authorization: Basic student1 password

### Start exam with glasses
GET localhost:8080/exams/start?key=393fb5c5-a7ed-477b-a95c-cd337af89ae9&glasses=true
Authorization: Basic student1 password

### Get question
GET localhost:8080/api/questions/1
Authorization: Basic student1 password

### Answer question in exam
POST localhost:8080/exams?key=393fb5c5-a7ed-477b-a95c-cd337af89ae9&option=3
Authorization: Basic student1 password
